name: Android CI

on:
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'android/**'

jobs:
  ktlint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: ktlint
        uses: ScaCap/action-ktlint@v1.8.0
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.SB_GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.SB_GITHUB_TOKEN }}
